# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
	@@ -17,22 +20,18 @@ jobs:
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2-beta
      with:
        version: 12 
    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v2.1.0
      with:
        # Yarn command
       cmd: install # npm install / yarn install
    - name: creating build
      run: yarn build
    - name: installing surge
      run: npm install -g surge
    - name: deploying on surge
      run: surge ./build sultan_project_005.surge.sh/ --token ${{secrets.SURGE_TOKEN}}
