# This is a basic workflow to help you get started with Actions

name: Deploying

# Controls when the action will run. 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Node.js envoirnment
        uses: actions/setup-node@v2.1.5
        with:
           # Version Spec of the version
           node-version: 12
           
      - name: Install Surge
        run: npm install -g surge

  
      - name: Build command
        run: npm run build
        
      - name: Deploy to surge
        run: surge ./build desajgjchh.surge.sh  --token ${{ secrets.SURGE_TOKEN }}
